---

- name: Setup Environment and Configure Certbot
  hosts: all
  become: true

  tasks:
    - name: Copy docker compose
      ansible.builtin.copy:
        src: /home/ubuntu/ansible/dependencies/docker-compose.yaml
        dest: /app/
        owner: root
        group: root
        mode: '0755'

    - name: Start Application Stack Docker Compose
      ansible.builtin.command:
        cmd: docker compose -f docker-compose.yaml up -d
        chdir: /app
      changed_when: false
