{
 "title": "Logs",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "backend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"app-backend-1\"} |= ``"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"app-frontend-1\"} |= ``"
    }
   ]
  },
  {
   "title": "Database",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"app-database-1\"} |= ``"
    }
   ]
  },
  {
   "title": "Var Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{service_name=\"varlogs\"} |= ``"
    }
   ]
  }
 ]
}