name: Terraform Apply

on:
  push:
    branches:
      - infra_main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write

env:
    TF_VAR_domain: ${{ secrets.DOMAIN }}
    TF_VAR_email: ${{ secrets.EMAIL }}

jobs:

  apply:
      name: Terraform Apply
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: ${{ vars.TERRAFORM_VERSION }}
            terraform_wrapper: false

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.ASSUME_ROLE }}
            role-session-name: github-action-role
            aws-region: ${{ secrets.REGION }}

        - name: Setup Backend
          working-directory: "dev/"
          run: |
            sed -i \
            -e "s|bucket = \".*\"|bucket = \"${{ secrets.BUCKET_NAME }}\"|" \
            -e "s|key = \".*\"|key = \"${{ vars.STATE_KEY }}\"|" \
            -e "s|region = \".*\"|region = \"${{ secrets.REGION }}\"|" \
            backend.tf

        - name: Terraform Init
          run: |
            terraform -chdir=dev init

        - name: Terraform Apply
          run: terraform -chdir=dev apply -auto-approve

        - name: Extract Ansible IP from Terraform Output
          id: extract_ip
          working-directory: dev
          run: |
            ANSIBLE_IP=$(terraform output -raw ansible_ip)
            echo "::add-mask::$ANSIBLE_IP"
            echo "ANSIBLE_IP=${ANSIBLE_IP}" >> $GITHUB_ENV
  
        - name: Update Secrets
          uses: jon-grey/github-actions-secrets-creator@v1
          with:
            name: ANSIBLE_IP
            value: ${{ env.ANSIBLE_IP }}
            pa_token: ${{ secrets.GH_TOKEN }}

        - name: Read and Mask Docker PEM File
          id: read_docker_pem
          working-directory: dev
          run: |
            DOCKER_PEM=$(cat docker.pem | base64 | tr -d '\n')
            echo "::add-mask::$DOCKER_PEM"
            echo "DOCKER_PEM=${DOCKER_PEM}" >> $GITHUB_ENV

        - name: Update Secrets
          uses: jon-grey/github-actions-secrets-creator@v1
          with:
            name: ANSIBlE_KEY
            value: ${{ env.DOCKER_PEM }}
            pa_token: ${{ secrets.GH_TOKEN }}

        
  
