name: Deploy Backend

permissions:
  contents: write


on:
  workflow_dispatch:

  push:
    branches:
      - deployment
    paths:
      - "backend/**"
      - "!backend/*.md"

jobs:
  Build-Push:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with: 
          context: "{{defaultContext}}:backend"
          push: true
          tags: ${{ secrets.BACKEND_IMAGE }}:1.${{ github.run_number }}

  Tag:
    name: Update Backend Tags
    needs: [Build-Push]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Tag
        run: |
          sed -i 's|image: backend-image|image: ${{ secrets.BACKEND_IMAGE }}:1.${{ github.run_number }}|' docker-compose.yaml

      - name: Commit Changes
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "$${{ github.actor }}@noreply.github.com"
          git add docker-compose.yaml
          git commit -m "Update Docker Image Tag to ${{ secrets.BACKEND_IMAGE }}:1.${{ github.run_number }}"
          git pull --rebase origin $BRANCH_NAME
          git push origin $BRANCH_NAME

